### PR TITLE
add indonesian translation

### PR DESCRIPTION
**Pull request by atoz-chevara**
this is my translation linux_logo for indonesian language

### CODE REVIEW

**Comment by tdi** [comment]
Great, when this is merged I can prepare a new Debian package with the translation.

**Comment by atoz-chevara** [comment]
whoa ... I almost sent it to the Debian BTS

**Comment by tdi** [comment]
@deater can you merge these two ?

**Comment by atoz-chevara** [comment]
@tdi I've sent it to [Debian BTS #833391](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=833391), but for BlankOn logo not included

**Pull request merged**
